package abuldovi.telegram.telegramApp.enums;

public enum BotState {
    START,
    SHOWEXPENSES,
    ADDVALUE,
    ADDCATEGORY,
    ADDSOURCE,
    SHOWYEARS,
    SELECTYEAR,
    SELECTDIFMONTH,
    SELECTMONTH,
    MONTHRESULT,
    THISMONTH,
    CHOOSECATEGORYEXPENSES,
    CHOOSECATEGORYEXPENSESPERIOD, 
    CATEGORYSHOWYEARS,
    CATEGORYTHISMONTH,
    CATEGORYSELECTYEAR,
    CATEGORYSELECTDIFMONTH,
    CATEGORYSELECTMONTH,
    CHOOSESOURCEEXPENSES,
    CHOOSESOURCEEXPENSESPERIOD,
    SOURCESHOWYEARS,
    SOURCETHISMONTH,
    SOURCESELECTYEAR,
    SOURCESELECTDIFMONTH,
    SOURCESELECTMONTH,
    EDITTRANSACTION,
    EDITEXPENSEADDVALUE,
    CHOOSECATEGORYEDITTRANSACTION,
    EDITCATEGORYEDITTRANSACTION,

    CHOOSESOURCEEDITTRANSACTION,
    EDITSOURCEEDITTRANSACTION,
    ADDVALUEEDITTRANSACTION



}

